# -*- coding: utf-8 -*-
"""Q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wMShK7zYeWia3ARNS9CNyDEGHppgOJfH
"""

import copy 
import math

def LFSR(C, S):
    L = len(S)
    fb = 0
    out = S[L-1]
    for i in range(0,L):
        fb = fb^(S[i]&C[i+1])
    for i in range(L-1,0,-1):
        S[i] = S[i-1]

    S[0] = fb
    return out

def FindPeriod(s):
    n = len(s)
    for T in range(1,n+1):
        chck = 0
        for i in range(0,n-T-1):
            if (s[i] != s[i+T]):
                chck += 1
                break
        if chck == 0:
            break
    if T > n/2:
        return n
    else:
        return T        

def PolPrune(P):
    n = len(P)
    i = n-1
    while (P[i] == 0):
        del P[i]
        i = i-1
    return i

def PolDeg(P):
    n = len(P)
    i = n-1
    while (P[i] == 0):
        i = i-1
    return i

# P gets Q
def PolCopy(Q, P):
    degP = len(P)
    degQ = len(Q)
    if degP >= degQ:
        for i in range(0,degQ):
            Q[i] = P[i]
        for i in range(degQ, degP):
            Q.append(P[i])
    else: # degP < deqQ
        for i in range(0,degP):
            Q[i] = P[i]
        for i in range(degP, degQ):
            Q[i] = 0
        PolPrune(Q)           


def FindPeriod(s):
    n = len(s)
    for T in range(1,n+1):
        chck = 0
        for i in range(0,n-T-1):
            if (s[i] != s[i+T]):
                chck += 1
                break
        if chck == 0:
            break
    if T > n/2:
        return n
    else:
        return T

def BM(s):
    n = len(s)

    C = []
    B = []
    T = []
    L = 0
    m = -1
    i = 0
    C.append(1)
    B.append(1)

    while(i<n):
        delta = 0
        clen = len(C)
        for j in range(0, clen):
            delta ^= (C[j]*s[i-j])
        if delta == 1:
            dif = i-m
            PolCopy(T, C)
            nlen = len(B)+dif
            if(clen >= nlen):
                for j in range(dif,nlen):
                    C[j] = C[j] ^ B[j-dif]
            else: # increase the degree of C
                for j in range(clen, nlen):
                    C.append(0)
                for j in range(dif, nlen):
                    C[j] = C[j] ^ B[j-dif]
            PolPrune(C)
            if L <= i/2:
                L = i+1-L
                m = i
                PolCopy(B, T)  
        i = i+1    
    return L, C 

length = 256

p1 = [1, 1, 0, 0, 1, 1, 1]
s1 = [1, 0, 1, 1, 0, 0,]

# generate a keystream with given polynomial and an arbitrary random seed
keystream1 = [0] * length
for i in range (0, length):
  keystream1[i] = LFSR(p1, s1)

print("First period ", FindPeriod(keystream1))
print("L and C(x): ", BM(keystream1))

period = FindPeriod(keystream1)
L, Cx = BM(keystream1)

if (pow(2, L) - 1) == period:
  print("It has the maximum period")
else:
  print("It couldn't reach the maximum period")

p2 = [1, 0, 1, 0, 0, 0, 1]
s2 = [1, 1, 0, 0, 0, 1]

# generate a keystream with given polynomial and an arbitrary random seed
keystream2 = [0] * length
for i in range (0, length):
  keystream2[i] = LFSR(p2, s2)

print("First period ", FindPeriod(keystream2))
print("L and C(x): ", BM(keystream2))

period = FindPeriod(keystream2)
L, Cx = BM(keystream2)

if (pow(2, L) - 1) == period:
  print("It has the maximum period")
else:
  print("It couldn't reach the maximum period")

p3 = [1, 0, 0, 1, 0, 1]
s3 = [1, 0, 0, 1, 1]

# generate a keystream with given polynomial and an arbitrary random seed
keystream3 = [0] * length
for i in range (0, length):
  keystream3[i] = LFSR(p3, s3)

print("First period ", FindPeriod(keystream3))
print("L and C(x): ", BM(keystream3))

period = FindPeriod(keystream3)
L, Cx = BM(keystream3)

if (pow(2, L) - 1) == period:
  print("It has the maximum period")
else:
  print("It couldn't reach the maximum period")