# -*- coding: utf-8 -*-
"""Q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Du5aJzaXuR-p0ls10oRCw8wKxjExQxj2
"""

N = 15220196297956469159
C = 6092243189299681137
e = pow(2, 16) + 1

def egcd(a, b):
    x,y, u,v = 0,1, 1,0
    while a != 0:
        q, r = b//a, b%a
        m, n = x-u*q, y-v*q
        b,a, x,y, u,v = a,r, u,v, m,n
    gcd = b
    return gcd, x, y

def modinv(a, m):
    gcd, x, y = egcd(a, m)
    if gcd != 1:
        return None  # modular inverse does not exist
    else:
        return x % m

# p = 3765204637  q = 4042329107
i = 3
while i**2 <= N:     
    if N%i==0:      
       p, q = i, N // i
       break
    else:
        i += 2

#p = 3765204637  
#q = 4042329107
phi = (p - 1) * (q - 1)

D = modinv(e, phi)
m = pow(C, D, N)

print("m without decoding:", m)
mx = m.to_bytes((m.bit_length() // 8 + 1 ), byteorder = 'big').decode('UTF-8')
print("Message is:", mx[::-1])
# Message is Eureka